### ISSUE TITLE
Add more verbose messages to the cli firmware updater

### ISSUE THREAD

**Issue by PKGeorgiev** [arduino/FirmwareUploader#6]
Currently the cli outputs only "Reading max payload size" or "Converting and flashing certificates from..." that make people wonder if the operation has completed successfully. It would be nice to have more detailed messages and indication of completion. For example:
- "Payload size is: xyz bytes"
- "Writing cert 1/x", "Writing cert 2/x" etc.
- "Write completed"

**Comment by umbynos** [comment]
The latest version on master currently supports `--log-level` flag (trace, debug, info, warn, error, fatal, panic (default "info")). By combining this flag with `-v` different levels of logging can be achieved
